### ISSUE TITLE
R CMD check S3 consistency

### ISSUE THREAD

**Issue by gvegayon** [KPDuBose/partyGames#2]
The message you are getting [here](https://github.com/KPDuBose/partyGames/actions/runs/4545734804/jobs/8013468315#step:5:178) has to do with how you are defining the S3 methods. Look at this section of [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Generic-functions-and-methods.)

**Comment by KPDuBose** [comment]
Thanks George! I was going to ask you about it in class, but this works great
